### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by guzuligo** [fishslot/video_loopback_for_webui#9]
I'm new to this. I add my input folder or file and output and try it. But, all I am getting is this error:

```
Traceback (most recent call last):
  File ".\AUTOMATIC1111\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File ".\AUTOMATIC1111\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File ".\AUTOMATIC1111\modules\img2img.py", line 169, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File ".\AUTOMATIC1111\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File ".\AUTOMATIC1111\extensions\video_loopback_for_webui\scripts\video_loopback.py", line 494, in run
    reference_img_que = TemporalImageBlender(
  File ".\AUTOMATIC1111\extensions\video_loopback_for_webui\scripts\video_loopback.py", line 33, in __init__
    self.window = deque(
  File ".\AUTOMATIC1111\extensions\video_loopback_for_webui\scripts\video_loopback.py", line 34, in <genexpr>
    self.read_image_resize(image_path_list[i])
IndexError: list index out of range
```

**Comment by fishslot** [comment]
It looks like this is because you don't have a picture in your input directory.
